### PR TITLE
Add two-input decoder example

### PR DESCRIPTION
**Pull request by maurobringolf**
I added one of the first examples of a composite gate from a lecture on digital circuits, the decoder. It reads `n` inputs and asserts exactly one of `2^n` outputs, sort of like a `switch` statement over all input combinations. I built the one with two inputs from `Not` and `And` gates.

Are there any tests for examples? I could not find any.

### CODE REVIEW

**Comment by DmitrySoshnikov** [comment]
Nice one! This is basically a version of a Demultiplexer (see descriptions, and truth tables of the [DMux](https://github.com/DmitrySoshnikov/hdl-js/blob/master/src/emulator/hardware/builtin-gates/DMux.js), [DMux4Way](https://github.com/DmitrySoshnikov/hdl-js/blob/master/src/emulator/hardware/builtin-gates/DMux4Way.js), and [DMux8Way](https://github.com/DmitrySoshnikov/hdl-js/blob/master/src/emulator/hardware/builtin-gates/DMux8Way.js)). Although, a demultiplexer operates on the manual "selector" input (which basically controls the output), while in your decoder, the output is determined automatically.

> lecture on digital circuits

What is this lecture, BTW? I'd be interested to read it as well.

> Are there any tests for examples? I could not find any.

There are no yet, these were just examples, but I think we can add `__tests__` directory, and do an automatic truth tables testing. See [example](https://github.com/DmitrySoshnikov/hdl-js/blob/master/src/emulator/hardware/__tests__/HDLClassFactory-test.js#L142-L163) of such testing, you can use the same `execOnData` method. Let me know if you want to add a test in this diff, otherwise I can merge this example.

**Comment by maurobringolf** [comment]
Ah yup now I see how it relates to the Dmux. I didn't know this one before, thanks! I'm okay with merging it like this, I asked just in case I missed the tests.

I took this example from the book **Introduction to Computing Systems: From Bits and Gates to C and Beyond** by Yale Patt (3.3.1, p.59), but I'm sure it exists in a lot of course material on the topic.

**Comment by DmitrySoshnikov** [comment]
OK, sounds good, we can introduce tests later, when will be adding more examples. Thanks for the example, and for the book recommendation!

**Comment by DmitrySoshnikov** [comment]
@maurobringolf, just an FYI: I setup an ability to test custom gates when a new example is added in #27. Feel free to add a test for the `Decoder` in case.

**Pull request merged**
